version: '3'
services:
  front:
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/
    ports:
      - 4200:4200
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
