version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: "${DB_HOST}"
    networks:
      - docker_network
    expose:
      - "${DB_PORT}"
    # ports:
    #   - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    # env_file:
    #   - .env
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./srcs
      dockerfile: Dockerfile
    container_name: api
    networks:
      - docker_network
    ports:
      - 3000:3000
    environment:
      DB_URL: "${DB_URL}"
      FORTYTWO_CLIENT_ID: "${FORTYTWO_CLIENT_ID}"
      FORTYTWO_CLIENT_SECRET: "${FORTYTWO_CLIENT_SECRET}"
      FORTYTWO_CLIENT_URL: "${FORTYTWO_CLIENT_URL}"
      FORTYTWO_CLIENT_URL_CALLBACK: "${FORTYTWO_CLIENT_URL_CALLBACK}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
    # env_file:
    #   - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - docker_network
    restart: on-failure
    ports:
      - 8080:8080

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - docker_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    ports:
      - 9000:9000 # http
      # - 9443:9443 # https

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PORTAINER_VOLUME_PATH}"
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DB_VOLUME_PATH}"

networks:
  docker_network:
    driver: bridge
