# Usar la imagen de Node.js 16.20.0 en Alpine como base
FROM node:16.20.0-alpine

# Instalar NestJS globalmente utilizando npm
RUN npm install -g @nestjs/cli

# Establecer el directorio de trabajo dentro del contenedor
#WORKDIR /app

EXPOSE 3000

# RUN npm install

# Comando para iniciar tu aplicación NestJS
# CMD ["npm", "run", "start"]
