version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: "${DB_HOST}"
    networks:
      - docker_network
    # expose:
    #   - "${DB_PORT}"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - docker_network
    restart: on-failure
    ports:
      - 8080:8080



volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DB_VOLUME_PATH}"

networks:
  docker_network:
    driver: bridge
