version: '3.8'
services:
  dev-db:
    image: postgres:15.3-alpine
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    networks:
    - docker_network
networks:
  docker_network:


