version: '3'
services:
  nginx:
    user: "${UID}:${GID}"
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_images:/usr/share/nginx/html/static_images
    ports:
      - "8081:8081"
#     user: "${UID}:${GID}"
# version: '3'
# services:
#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./static_images:/usr/share/nginx/html/static_images
#     ports:
#       - "80:80"
